AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure creation

Resources: 
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security group for the ec2 instance
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 
  
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref Ec2SecurityGroup
      KeyName: tmp-key
      ImageId: 'ami-052efd3df9dad4825'
      InstanceType: t3.micro
